<?php

namespace PhpBoot\Workflow\Process\Nodes;

use PhpBoot\Workflow\Exceptions\ProcessDefineException;
use PhpBoot\Workflow\Process\ProcessContext;
use PhpBoot\Workflow\Process\ProcessEngine;
use PhpBoot\Workflow\Process\Traits\NoOutput;
use PhpBoot\Workflow\Process\Traits\SingleInput;

class EndEvent extends ProcessNode
{
    public function __construct($nodeName){
        parent::__construct($nodeName);
    }

    public function handle(ProcessContext $context, ProcessEngine $engine)
    {
        $engine->triggerEndEvent();
        parent::handle($context, $engine); // TODO: Change the autogenerated stub
    }

    use SingleInput;
    use NoOutput;
}